### ISSUE TITLE
Hi i am Getting this Error

### ISSUE THREAD

**Issue by Gantaios** [sgr-ksmt/PullToDismiss#17]
![screen shot 2017-01-18 at 7 16 41 pm](https://cloud.githubusercontent.com/assets/18135450/22066406/e21a5094-ddb2-11e6-9e90-af5af66890c8.png)

i gave outlet for tableView but still getting the error. I am using custom TableViewController

**Comment by sgr-ksmt** [comment]
@Gantaios Please check SampleViewController's `tableView` why it was nil this line.
This is probably not PullToDismiss fault.

<img width="361" alt="2017-01-18 23 30 53" src="https://cloud.githubusercontent.com/assets/9350581/22067814/2f5e0224-ddd6-11e6-8918-0c9c13abb6e4.png">
