### ISSUE TITLE
Crash in iOS9 when closed ViewController having pullToDismiss instance.

### ISSUE THREAD

**Issue by cokaholic** [sgr-ksmt/PullToDismiss#18]
Xcode Version : 8.2.1
Device : iPhone6（iOS9.1.3）, iPhone6s Simulator（iOS9.0）
Frequency : 10 / 10

**Comment by cokaholic** [comment]
I'm sorry. This crash problem is my fault.

**Comment by sgr-ksmt** [comment]
@cokaholic Could you please more information(crash log, sample code, etc..) if possible 🙇 .

**Comment by cokaholic** [comment]
[PullToDismissTest.zip](https://github.com/sgr-ksmt/PullToDismiss/files/768320/PullToDismissTest.zip)

**Comment by cokaholic** [comment]
This is my sample codes about your library.
Please run it in your simulator or device.
Occurring error type is EXC_BAD_ACCESS.

**Comment by sgr-ksmt** [comment]
@cokaholic Thanks!!!
I found bugs and will fix soon.. 🙇 
Please add temporary code in your view controller's `deinit` until I publish new version of `PullToDismiss`

```swift
final class WebViewController: UIViewController {
    // ...

    deinit {
        webView.scrollView.delegate = nil
    }
}
```

**Comment by sgr-ksmt** [comment]
@cokaholic 
I just published v1.1.1 . please update PullToDismiss's version 🙇 
If this problem still appears, please let me know.

**Comment by cokaholic** [comment]
Thank you so much!

**Comment by cokaholic** [comment]
I tried v1.1.1 on my device now.
This bug has fixed!
Thank you for your hard work!

**Comment by sgr-ksmt** [comment]
🔚
